M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu20.04.1} date pon 12 dec 2022 12:35:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-12T12:35:40+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X142.24Y-89.535
T0
M30
